[server]
headless = true
port = 8501
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#2e6c80"
backgroundColor = "#F5C9E8"
secondaryBackgroundColor = "#ffffff"
textColor = "#262730"
